source 'https://rubygems.org'

gem 'rails', '4.0.3'
gem 'sqlite3'

group :assets do
  gem 'sprockets-rails'
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.0.1'
gem 'puma'
gem 'redis'
